import { metrics } from './experience';

export type DeviceType = 'laptop' | 'phone';

export interface ProjectTexture {
  readonly srcSet: string;
  readonly placeholder: string;
}

export interface ProjectModel {
  readonly type: DeviceType;
  readonly alt: string;
  readonly textures: readonly ProjectTexture[];
}

/** Where a project came from, so the two kinds are never conflated. */
export type ProjectKind = 'work' | 'personal';

export interface Project {
  readonly slug: string;
  /** Full title, used as the case-study heading and meta title. */
  readonly title: string;
  /** Short name for compact surfaces like the poster and nav. */
  readonly shortTitle: string;
  /** One-sentence summary shown on the home page and in meta descriptions. */
  readonly description: string;
  /** What I was actually responsible for. */
  readonly roles: readonly string[];
  readonly kind: ProjectKind;
  /** Technologies actually used, rendered as chips. */
  readonly stack: readonly string[];
  /**
   * OKLCH hue for this project's accent, so each case study reads as its own
   * thing while still using the site's colour system.
   */
  readonly hue: string;
  readonly liveUrl?: string;
  readonly repoUrl?: string;
  /** Why a live link may not get a visitor very far, or why there is no source link. */
  readonly access?: string;
  /** When the case study last changed materially, `YYYY-MM-DD`. Feeds the sitemap. */
  readonly updatedAt: string;
}

export const projectPath = (slug: string) => `/projects/${slug}`;

/** Social preview image, generated by scripts/og-images.cjs. */
export const projectOgImage = (slug: string) => `/og/${slug}.png`;

/**
 * Home-page ordering is the order of this array; `alternate` layout is derived
 * from the index rather than hardcoded per card.
 */
export const projects = [
  {
    slug: 'personal-vault',
    title: 'Personal Vault — Encrypted Archive on a $0 Budget',
    shortTitle: 'Personal Vault',
    description:
      'A photo, video and document archive that costs nothing to run: an end-to-end-encrypted document vault, a self-hosted photo engine, verified backups and a live health dashboard, each with its failure modes written down.',
    roles: [
      'Architecture & Threat Model',
      'Client-side Cryptography',
      'Infrastructure & Backups',
      'Full-stack Development',
    ],
    kind: 'personal',
    stack: [
      'Next.js 16',
      'TypeScript',
      'Web Crypto',
      'Supabase',
      'Oracle Cloud',
      'Ansible',
      'restic',
      'Tailscale',
      'Playwright',
    ],
    hue: '28',
    liveUrl: 'https://vault-amber-five.vercel.app',
    repoUrl: 'https://github.com/JatinMangla/personal-vault',
    access: 'Private by design — the live link shows the sign-in screen.',
    updatedAt: '2026-09-24',
  },
  {
    slug: 'mera-monitor',
    title: 'Mera Monitor — Workforce Analytics Platform',
    shortTitle: 'Mera Monitor',
    description: `Frontend work on a workforce-analytics SaaS used by ${metrics.activeUsers.value} people: data-heavy dashboards and reports, Redux and React Query state, and Microsoft/Google single sign-on.`,
    roles: [
      'Frontend Development',
      'React.js & Redux',
      'SSO Integration (MSAL/OAuth)',
      'Load-time Optimisation',
    ],
    kind: 'work',
    stack: [
      'React.js',
      'Redux',
      'React Query',
      'Formik',
      'ApexCharts',
      'SignalR',
      'MSAL',
      'SCSS',
    ],
    hue: '202.24',
    liveUrl: 'https://meramonitor.com',
    updatedAt: '2026-09-24',
  },
  {
    slug: 'analytics-mcp-server',
    title: 'Analytics MCP Server — Claude over OAuth 2.1',
    shortTitle: 'Analytics MCP Server',
    description:
      'A remote MCP server that lets Claude query a workforce-analytics API, with its own OAuth 2.1 authorization server, safety rails on every sensitive tool, and a port from a long-running process to serverless.',
    roles: [
      'Protocol & API Design',
      'OAuth 2.1 Authorization Server',
      'Serverless Port',
      'LLM Tool Safety',
    ],
    kind: 'personal',
    stack: [
      'TypeScript',
      'Node.js',
      'MCP SDK',
      'OAuth 2.1 + PKCE',
      'Upstash Redis',
      'Vercel Functions',
    ],
    hue: '255',
    access:
      'Built against a production API that holds employee data, so the source and endpoint stay private; this write-up covers the design only.',
    updatedAt: '2026-09-24',
  },
  {
    slug: 'careerpilot-ai',
    title: 'CareerPilot AI — Personal Career Copilot',
    shortTitle: 'CareerPilot AI',
    description:
      'An AI career copilot that finds jobs across 120+ company boards, tailors applications for approval, triages a Gmail inbox and runs mock interviews — on Gemini’s free tier, with the usage guards that makes necessary.',
    roles: [
      'Full-stack Development',
      'LLM Integration (Gemini)',
      'Serverless API Design',
      'Sync & Data Integrity',
    ],
    kind: 'personal',
    stack: [
      'Next.js 14',
      'TypeScript',
      'Tailwind CSS',
      'Google Gemini',
      'Upstash Redis',
      'IMAP',
      'Vercel Functions',
    ],
    hue: '295',
    liveUrl: 'https://careerpilot-ai-beige-tau.vercel.app',
    repoUrl: 'https://github.com/JatinMangla/CareerPilot-AI',
    access: 'Single-user by design — the live link shows the sign-in screen.',
    updatedAt: '2026-09-24',
  },
  {
    slug: 'kundli-predict',
    title: 'Kundli Predict — Vedic Astrology Engine with AI Readings',
    shortTitle: 'Kundli Predict',
    description:
      'Computes complete birth charts, dashas, transits and a Hindu calendar in the browser, then has Gemini read the whole chart — so the maths is exact and testable, and only the interpretation is generated.',
    roles: [
      'Full-stack Development',
      'Astronomical Computation Engine',
      'LLM Integration (Gemini)',
      'Bilingual UI (English/Hindi)',
    ],
    kind: 'personal',
    stack: [
      'Next.js 15',
      'TypeScript',
      'Tailwind CSS 4',
      'astronomy-engine',
      'Google Gemini',
      'Dexie / IndexedDB',
      'Auth.js v5',
      'Vitest',
    ],
    hue: '75',
    liveUrl: 'https://predict-five-blue.vercel.app',
    repoUrl: 'https://github.com/JatinMangla/predict',
    access:
      'Sign-in is restricted to the owner’s account. Profiles stay on the device; readings send the computed chart to Gemini.',
    updatedAt: '2026-09-24',
  },
  {
    slug: 'screen-coach',
    title: 'Screen Coach — Screen Time Monitoring',
    shortTitle: 'Screen Coach',
    description:
      'Developed responsive UI and RESTful APIs for a screen-time monitoring tool optimized for low-memory devices using Node.js and MongoDB.',
    roles: [
      'Frontend Development',
      'Node.js & MongoDB APIs',
      'Performance Optimization',
      'Real-time Data',
    ],
    kind: 'work',
    stack: ['JavaScript', 'Node.js', 'Express.js', 'MongoDB', 'REST'],
    hue: '150',
    liveUrl: 'https://www.myscreencoach.com',
    updatedAt: '2026-08-20',
  },
] as const satisfies readonly Project[];

export type ProjectSlug = (typeof projects)[number]['slug'];

/**
 * Generic over the slug so callers get the exact record back, not a union of
 * all four. Without it, fields only some projects carry — `repoUrl`, `access` —
 * are invisible to the case study that actually has them.
 */
export function getProject<S extends ProjectSlug>(slug: S) {
  const project = projects.find(entry => entry.slug === slug) as
    | Extract<(typeof projects)[number], { slug: S }>
    | undefined;

  if (!project) throw new Error(`Unknown project slug: ${slug}`);

  return project;
}

/** Projects that have a 3D device preview; the rest render a poster instead. */
export const hasDeviceModel = (slug: ProjectSlug) =>
  slug === 'mera-monitor' || slug === 'screen-coach';
